# Generated by Django 2.2.1 on 2019-06-01 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_category', to='products.Category'),
        ),
    ]
