# Generated by Django 2.2.1 on 2019-06-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
